steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/loopbin/expresso-multistages:1.1.0','-f','./expresso/Dockerfile.multistage', './expresso' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/loopbin/expresso-multistages:1.1.0']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run',
    'deploy', 'expresso-multistages',
    '--image', 'eu.gcr.io/loopbin/expresso-multistages:1.1.0',
    '--region', 'europe-west1',
    '--port', '3000',
    '--cpu', '1',
    '--max-instances','1',
    '--min-instances','0',
    '--memory','512Mi',
    '--concurrency','1000',
    '--allow-unauthenticated',
    ]