version: '3.1'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      MONGODB_USER: admin
      MONGODB_PASSSWORD: admin
      MONGODB_HOST: mongo
    volumes:
      - .:/app
    networks:
      - container-link


  mongo:
    image: mongo
    restart: always
    ports:
      - "27016:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - container-link
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

networks:
  container-link:
volumes:
  mongodb:
  mongodb_config:


